### ISSUE TITLE
Pretrained model 

### ISSUE THREAD

**Issue by abhigoku10** [vita-epfl/detection-attributes-fields#4]
@taylormordan  thanks for sharing the code base and the wonderful work is it possible to share the pretrained model to test the results ??
Thanks in advance

**Comment by taylormordan** [comment]
Hello @abhigoku10 , you can find a trained model [here](https://drive.google.com/file/d/1lkYIzre4xhOvo6-lqVt_lW-IwVtW6JDL/view?usp=sharing).

**Comment by nabil97-anouar** [comment]
Hello mr.@taylormordan thank you very much for your Information, I succeed to generate the Json file, but I need to figure out how to generate some attributes in the video!

**Comment by abhigoku10** [comment]
@nabil97-anouar can you please share the inference.py / demo.py which generates the results ?

**Comment by Affanabbbas** [comment]
hi 
can you plz help me with this issue?

python3 -m openpifpaf.train: error: unrecognized arguments: --datasets jaad --jaad-root-dir /content/drive/MyDrive/jaad/JAAD_clips/ --jaad-subset default --jaad-training-set train --jaad-validation-set val --pifpaf-pretraining --detection-bias-prior 0.01 --jaad-head-upsample 2 --jaad-pedestrian-attributes all --fork-normalization-operation power --fork-normalization-duplicates 35 --attribute-regression-loss l1 --attribute-focal-gamma 2

This is what I get after running the script.
How have u donwloaded the dataset and what have you done with the annotations?

**Comment by nabil97-anouar** [comment]
hi,
Check my repository :https://colab.research.google.com/drive/1zAzjN8jGbny0h574BZ7vShIewxXHFIFr
you have to download the dataset and put the right path for each parameter : --datasets jaad --jaad-root-dir...

**Comment by Affanabbbas** [comment]
Thanks for your response.Please allow access for it.
    On Thursday, June 9, 2022, 04:04:08 PM GMT+5, Anouar Nabil ***@***.***> wrote:  
 
 


hi,
Check my repository :https://colab.research.google.com/drive/1zAzjN8jGbny0h574BZ7vShIewxXHFIFr
you have to download the dataset and put the right path for each parameter : --datasets jaad --jaad-root-dir...

**Comment by nabil97-anouar** [comment]
it's done check ur email

**Comment by Affanabbbas** [comment]
Thanks a lot    On Thursday, June 9, 2022, 04:30:55 PM GMT+5, Anouar Nabil ***@***.***> wrote:  
 
 


it's done check ur email

**Comment by Affanabbbas** [comment]
Hi bro,I am still getting this error.
Can you plz help me out?
usage: python3 -m openpifpaf.train [options]python3 -m openpifpaf.train: error: unrecognized arguments: --jaad-root-dir /content/JAAD --jaad-subset default --jaad-training-set train --jaad-validation-set val --pifpaf-pretraining --detection-bias-prior 0.01 --jaad-head-upsample 2 --jaad-pedestrian-attributes all --fork-normalization-operation power --fork-normalization-duplicates 35 --attribute-regression-loss l1 --attribute-focal-gamma 2
    On Thursday, June 9, 2022, 04:36:50 PM GMT+5, Affan Abbas ***@***.***> wrote:  
 
  
Thanks a lot    On Thursday, June 9, 2022, 04:30:55 PM GMT+5, Anouar Nabil ***@***.***> wrote:  
 
 


it's done check ur email
